In [141]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, confusion_matrix
from sklearn.preprocessing import StandardScaler

In [142]:
def model_building(file_name):
    dataset = pd.read_csv(file_name)
    dataset.drop('Id',axis=1,inplace=True)
    dataset.drop_duplicates(inplace=True)
    X = dataset.iloc[:,:4]
    Y = dataset.iloc[:,-1]
    scaler = StandardScaler()
    X_scaled = scaler.fit_transform(X)
    X_train, X_test, y_train, y_test = train_test_split(X_scaled,Y,test_size=0.2,random_state=42)
    model = LogisticRegression()
    model.fit(X_train,y_train)
    y_pred = model.predict(X_test)
    confusion_mat = confusion_matrix(y_test,y_pred)
    accuracy = accuracy_score(y_test,y_pred)*100
    return confusion_mat, accuracy, scaler, model

In [149]:
def user_prediction(scaler, model):
    sepal_length = float(input("Enter the sepal length: "))
    sepal_width = float(input("Enter the sepal width: "))
    petal_length = float(input("Enter the petal length: "))
    petal_width = float(input("Enter the petal width: "))
    input_data = pd.DataFrame([[sepal_length, sepal_width, petal_length, petal_width]])
    input_data_scaled = scaler.transform(input_data)
    prediction = model.predict(input_data_scaled)
    print('Prediction:', prediction)

In [150]:
conf_mat, accuracy, scaler, model = model_building('iris.csv')
print('Accuracy:', accuracy)
print('Confusion Matrix:')
print(confusion_mat)

Accuracy: 96.66666666666667
Confusion Matrix:
[[11  0  0]
 [ 0  9  1]
 [ 0  0  9]]


In [151]:
user_prediction(scaler, model)

Enter the sepal length: 5.1
Enter the sepal width: 3.5
Enter the petal length: 1.4
Enter the petal width: 0.2
Prediction: ['Iris-setosa']


C:\Users\Public\Anaconda\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
